<<<<<<< HEAD
<<<<<<< HEAD
theme: jekyll-theme-cayman
=======
theme: jekyll-theme-slate
>>>>>>> eb66c6c... Set theme jekyll-theme-slate
=======
theme: jekyll-theme-cayman
>>>>>>> 00dcc15... Set theme jekyll-theme-cayman
